aux_links:
  "RHCSA Open Guide source":
    - "//github.com/rbong/rhcsa-open-guide"
back_to_top: true
back_to_top_text: "Back to top"
baseurl: /rhcsa-open-guide
color_scheme: rhcsa
description: Open guide for RHCSA (EX200).
exclude:
  - docs
  - README.md
  - LICENSE.txt
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - vale-styles
footer_content: 'Copyright &copy; 2022 Roger Bongers. Distributed by an <a href="https://github.com/rbong/rhcsa-open-guide/tree/master/LICENSE.txt">MIT license.</a>'
remote_theme: just-the-docs/just-the-docs
title: RHCSA Open Guide
url: https://rbong.github.io
