name: HTMLProofer
on:
  - push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Build
        run: bundle exec jekyll build
      - name: HTMLProofer
        run: bundle exec htmlproofer --assume-extension ./_site
